sudo: required
services:
  - docker

before_install:
  - docker build -t achaukin/docker-nodeapp -f Dockerfile.dev .

script:
  - docker run -rm achaukin/docker-nodeapp CI=true npm run test

language: node_js