sudo: required
services:
  - docker

before_install:
  - docker build -t achaukin/docker-nodeapp -f Dockerfile.dev .

script:
  - docker run --rm -e CI=true achaukin/docker-nodeapp npm run test

language: node_js
node_js:
  - "12"