sudo: required
services:
  - docker

before_install:
  - docker build -t achaukin/docker-nodeapp -f Dockerfile.dev .

script:
  - docker run -e CI=true --mount type=bind,src="$PWD",dst=/app achaukin/docker-nodeapp npm run test

language: generic